---

- name: Apply interface description via eAPI 
  hosts: arista

  tasks:
    - name: Update Interface Description
      eos_interface: name=Ethernet3 description="*** IN USE ***"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Create access port in vlan 80
      eos_switchport: name=Ethernet3 mode=access access_vlan=80
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
