---

- name: Create trunk via eAPI 
  hosts: arista

  tasks:
    - name: Create trunk port
      eos_switchport: name=Ethernet3 mode=trunk trunk_native_vlan=1 trunk_allowed_vlans=80,81,82
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
