---

- name: Default interface via eAPI 
  hosts: arista

  tasks:
    - name: Update Interface Description
      eos_interface: name=Ethernet3 description=""
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Default switchport parameters
      eos_switchport: name=Ethernet3 mode=access access_vlan=1 trunk_allowed_vlans=1-4094
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Remove VLANs 80-82
      eos_vlan: name={{ item.name }} vlanid={{ item.vlanid }} state=absent
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
        - {name: ATHENS, vlanid: 80}
        - {name: DALLAS, vlanid: 81}
        - {name: TYLER, vlanid: 82}
